Player accessibility improvements.
ucfopen/secret-spreadsheet-materia-widget pull request #73
Opened 2023-07-11 21:01 UTC by FrenjaminBanklin

Closes #27.
Added tab indices to numerous elements so they are reachable in the tab order.

Adjusted aria text for multiple elements and added modest visual effects to indicate when non-interactive elements have focus.

Added keyup handler on 'view question' link for keyboard support.

Disabled autocomplete on table inputs.

Added logic to toggle inert on the game board when a popup is visible.

2023-07-12 19:17 UTC, cayb0rg reviewed
Keyboard accessibility is great. VoiceOver works well, too. Just a few things I noticed: 
* “Input the missing data to complete the spreadsheet” is still reachable by VoiceOver with the help or view question dialog visible
* The table is missing row headers
* Doesn’t recognize when the user has left the table using the VoiceOver modifier + arrow keys so the number of cells filled doesn’t update until “View Question” is focused
* I wonder if there should be some mention of the question marks as signifiers for blank cells in the screenreader instructions. It might be obvious once the cell says “edit text, blank” but almost might not be.

2023-07-12 21:22 UTC, clpetersonucf commented
I agree with Cay's points. The two things I was going to mention:

- Like Cay said, the label for empty cells should probably better indicate the intended action instead of just reading "question mark"
- The submit button may benefit from a description indicating completion state, or have a confirmation dialog if there are still empty cells before submitting.

2023-07-18 18:59 UTC, FrenjaminBanklin commented
I may need a bit more context re: the table missing row headers. Depending on whether the author chose to render the table as a regular table or as a spreadsheet, the actual structure of the table may end up having an extra row and column attached to it that'll throw off whatever we do anyway.

I'm also not sure if there's an event we can pick up that would allow us to do things based on the users moving away from the table using VO modifier keys. The cells are set up to save their answers and update the relevant numbers whenever they're blurred anyway, and if using the VO keys to move focus around doesn't already trigger a blur I'm not sure if we can do anything else.

2023-07-24 20:08 UTC, cayb0rg commented
Re: missing table headers. Not a big deal, but if it's in spreadsheet mode, then the first column's cells "1", "2", etc. should have row headers. See [lines 105-119 of components/player/table.js](https://github.com/ucfopen/secret-spreadsheet-materia-widget/blob/4f438b5f9c148137298b3afe659448def2453793/src/components/player/table.js#L105).

As far as the number of cells not updating, the only solution I can think of is calling ``saveAnswer`` in the cell's ``handleChange`` function if the cell has some value.

2023-07-27 14:46 UTC, clpetersonucf requested changes
The final changes are great. I think it's good to go, with two minor changes requested:

- The submit button can be clicked before completion, but it doesn't have a `cursor: pointer` or hover style applied in the incomplete state. You can accidentally submit the widget early, assuming the button isn't actually interactive. It should at least be responsive to the mouse cursor to indicate it can be clicked.
- The MWDK dependency should be updated to `2.5.2` and the lockfile regenerated accordingly

2023-08-02 15:04 UTC, clpetersonucf approved these changes
Ship it

2023-08-02 15:05 UTC, merged